// 전화번호
// 찜 갯수(내가 누르면 1개 올라가고 취소하면 1개 내려가고)
// 결제방법 => 바로결제, 만나서결제
// 배달시간 ????? 목데이터 vs 실제 시간
// 가게 이미지

// 판매메뉴??????????

export const stores = [
  {
    id: 1,
    star: "(4.6)",
    tip: "0~2000원",
    lowest: "10000원",
    name: "귀한족발 OO점",
    type: "bossam",
    sells: ["bossam", "night", "meat"],
  },
  {
    id: 2,
    star: "(4.9)",
    tip: "0~2500원",
    lowest: "14000원",
    name: "마왕족발 OO점",
    type: "bossam",
    sells: ["bossam", "night", "meat"],
  },
  {
    id: 3,
    star: "(4.7)",
    tip: "0~3200원",
    lowest: "14000원",
    name: "구구족 OO점",
    type: "bossam",
    sells: ["bossam", "night", "meat"],
  },
  {
    id: 4,
    star: "(4.7)",
    tip: "0~3400원",
    lowest: "10000원",
    name: "두찜 OO점",
    type: "jjigae",
    sells: ["jjigae", "per1", "night", "rice"],
  },
  {
    id: 5,
    star: "(4.7)",
    tip: "0~1600원",
    lowest: "13000원",
    name: "사위식당 OO점",
    type: "jjigae",
    sells: ["per1", "jjigae", "rice"],
  },
  {
    id: 6,
    star: "(4.9)",
    tip: "0~2200원",
    lowest: "9000원",
    name: "열정국밥 OO점",
    type: "jjigae",
    sells: ["per1", "jjigae", "rice"],
  },
  {
    id: 7,
    star: "(4.6)",
    tip: "0~3000원",
    lowest: "14000원",
    name: "육회한녀석들 OO점",
    type: "sushi",
    sells: ["per1", "sushi", "night"],
  },
  {
    id: 8,
    star: "(4.6)",
    tip: "0~3300원",
    lowest: "10000원",
    name: "연돈 OO점",
    type: "sushi",
    sells: ["sushi", "per1", "rice", "lunchbox"],
  },
  {
    id: 9,
    star: "(4.8)",
    tip: "0~1300원",
    lowest: "10000원",
    name: "어사출도 OO점",
    type: "sushi",
    sells: ["sushi", "per1", "night"],
  },
  {
    id: 10,
    star: "(4.6)",
    tip: "0~3000원",
    lowest: "12000원",
    name: "미친피자 OO점",
    type: "pizza",
    sells: ["pizza", "night"],
  },
  {
    id: 11,
    star: "(4.6)",
    tip: "0~2600원",
    lowest: "9000원",
    name: "반올림피자 OO점",
    type: "pizza",
    sells: ["pizza", "night"],
  },
  {
    id: 12,
    star: "(4.6)",
    tip: "0~1700원",
    lowest: "12000원",
    name: "도미노피자 OO점",
    type: "pizza",
    sells: ["pizza", "night"],
  },
  {
    id: 13,
    star: "(4.6)",
    tip: "0~1500원",
    lowest: "12000원",
    name: "파파존스 OO점",
    type: "pizza",
    sells: ["pizza", "night"],
  },
  {
    id: 14,
    star: "(4.7)",
    tip: "0~1600원",
    lowest: "9000원",
    name: "제육의달인 OO점",
    type: "meat",
    sells: ["per1", "meat", "rice", "lunchbox"],
  },
  {
    id: 15,
    star: "(4.9)",
    tip: "0~2800원",
    lowest: "9000원",
    name: "마장동김씨 OO점",
    type: "meat",
    sells: ["meat", "per1", "rice", "lunchbox"],
  },
  {
    id: 16,
    star: "(4.7)",
    tip: "0~1900원",
    lowest: "9000원",
    name: "배달돼지 OO점",
    type: "meat",
    sells: ["per1", "meat", "rice", "lunchbox"],
  },
  {
    id: 17,
    star: "(4.6)",
    tip: "0~2900원",
    lowest: "10000원",
    name: "지랄닭발 OO점",
    type: "night",
    sells: ["night", "per1"],
  },
  {
    id: 18,
    star: "(4.6)",
    tip: "0~1900원",
    lowest: "14000원",
    name: "매콤쭈선생 OO점",
    type: "night",
    sells: ["night", "per1"],
  },
  {
    id: 19,
    star: "(4.6)",
    tip: "0~1100원",
    lowest: "14000원",
    name: "왔다닭발 OO점",
    type: "night",
    sells: ["night", "per1"],
  },
  {
    id: 20,
    star: "(4.7)",
    tip: "0~2100원",
    lowest: "14000원",
    name: "포크너 OO점",
    type: "pasta",
    sells: ["pasta", "per1"],
  },
  {
    id: 21,
    star: "(4.6)",
    tip: "0~1700원",
    lowest: "9000원",
    name: "아웃백 OO점",
    type: "pasta",
    sells: ["pasta"],
  },
  {
    id: 22,
    star: "(4.6)",
    tip: "0~2400원",
    lowest: "10000원",
    name: "버텍스 OO점",
    type: "pasta",
    sells: ["pasta", "per1"],
  },
  {
    id: 23,
    star: "(5.0)",
    tip: "0~1500원",
    lowest: "14000원",
    name: "BHC OO점",
    type: "chicken",
    sells: ["chicken", "night"],
  },
  {
    id: 24,
    star: "(4.9)",
    tip: "0~1600원",
    lowest: "12000원",
    name: "교촌치킨 OO점",
    type: "chicken",
    sells: ["chicken", "night"],
  },
  {
    id: 25,
    star: "(4.9)",
    tip: "0~3300원",
    lowest: "10000원",
    name: "후라이드중독 OO점",
    type: "chicken",
    sells: ["chicken", "night"],
  },
  {
    id: 26,
    star: "(4.6)",
    tip: "0~3000원",
    lowest: "11000원",
    name: "짬뽕지존 OO점",
    type: "jjajang",
    sells: ["per1", "jjajang"],
  },
  {
    id: 27,
    star: "(4.5)",
    tip: "0~3500원",
    lowest: "11000원",
    name: "달려라짜장 OO점",
    type: "jjajang",
    sells: ["per1", "jjajang"],
  },
  {
    id: 28,
    star: "(4.9)",
    tip: "0~2700원",
    lowest: "13000원",
    name: "홍콩반점 OO점",
    type: "jjajang",
    sells: ["per1", "jjajang"],
  },
  {
    id: 29,
    star: "(4.9)",
    tip: "0~1200원",
    lowest: "13000원",
    name: "까몬 OO점",
    type: "asian",
    sells: ["per1", "asian", "per1"],
  },
  {
    id: 30,
    star: "(5.0)",
    tip: "0~3400원",
    lowest: "9000원",
    name: "포메인 OO점",
    type: "asian",
    sells: ["per1", "asian", "rice"],
  },
  {
    id: 31,
    star: "(4.7)",
    tip: "0~2100원",
    lowest: "14000원",
    name: "땀땀 OO점",
    type: "asian",
    sells: ["per1", "asian", "rice"],
  },
  {
    id: 32,
    star: "(4.6)",
    tip: "0~1700원",
    lowest: "9000원",
    name: "본죽 OO점",
    type: "rice",
    sells: ["rice", "lunchbox", "per1"],
  },
  {
    id: 33,
    star: "(4.6)",
    tip: "0~2400원",
    lowest: "10000원",
    name: "고기듬뿍통큰비빔밥 OO점",
    type: "rice",
    sells: ["per1", "rice", "lunchbox"],
  },
  {
    id: 34,
    star: "(5.0)",
    tip: "0~1500원",
    lowest: "14000원",
    name: "국수나무 OO점",
    type: "rice",
    sells: ["rice", "per1"],
  },
  {
    id: 35,
    star: "(4.9)",
    tip: "0~1600원",
    lowest: "12000원",
    name: "본도시락 OO점",
    type: "lunchbox",
    sells: ["lunchbox", "rice", "per1"],
  },
  {
    id: 36,
    star: "(4.9)",
    tip: "0~3300원",
    lowest: "10000원",
    name: "한솥도시락 OO점",
    type: "lunchbox",
    sells: ["lunchbox", "per1", "rice"],
  },
  {
    id: 37,
    star: "(4.6)",
    tip: "0~3000원",
    lowest: "11000원",
    name: "핵밥 OO점",
    type: "lunchbox",
    sells: ["per1", "rice", "lunchbox"],
  },
  {
    id: 38,
    star: "(4.5)",
    tip: "0~3500원",
    lowest: "11000원",
    name: "우리할매떡볶이 OO점",
    type: "tteokbokki",
    sells: ["per1", "tteokbokki"],
  },
  {
    id: 39,
    star: "(4.9)",
    tip: "0~2700원",
    lowest: "13000원",
    name: "신전떡볶이 OO점",
    type: "tteokbokki",
    sells: ["per1", "tteokbokki"],
  },
  {
    id: 40,
    star: "(4.9)",
    tip: "0~1200원",
    lowest: "13000원",
    name: "떡순튀 OO점",
    type: "tteokbokki",
    sells: ["per1", "tteokbokki"],
  },
  {
    id: 41,
    star: "(5.0)",
    tip: "0~3400원",
    lowest: "9000원",
    name: "스타벅스 OO점",
    type: "cafe",
    sells: ["cafe"],
  },
  {
    id: 42,
    star: "(4.6)",
    tip: "0~2000원",
    lowest: "10000원",
    name: "요거트월드 OO점",
    type: "cafe",
    sells: ["cafe"],
  },
  {
    id: 43,
    star: "(4.2)",
    tip: "0~3200원",
    lowest: "11000원",
    name: "파리바게트 OO점",
    type: "cafe",
    sells: ["cafe"],
  },
  {
    id: 44,
    star: "(4.2)",
    tip: "0~2600원",
    lowest: "12000원",
    name: "맥도날드 OO점",
    type: "fastfood",
    sells: ["per1", "fastfood"],
  },
  {
    id: 45,
    star: "(4.4)",
    tip: "0~1500원",
    lowest: "8000원",
    name: "버거킹 OO점",
    type: "fastfood",
    sells: ["per1", "fastfood"],
  },
  {
    id: 46,
    star: "(4.6)",
    tip: "0~1200원",
    lowest: "12000원",
    name: "맘스터치 OO점",
    type: "fastfood",
    sells: ["per1", "chicken", "fastfood"],
  },
];
